[build]
  publish = "dist"
  command = "npm run generate"

# Proxy API requests to the countries API
[[redirects]]
  from = "/api/*"
  to = "https://www.apicountries.com/:splat"
  status = 200
  force = true
  headers = {Accept = "application/json", Content-Type = "application/json"}

